### ISSUE TITLE
Can you update for AndroidX?

### ISSUE THREAD

**Issue by akatriel** [delay/flutter_firebase_auth_example#1]
Building after running ```flutter packages get``` fails because of AndroidX incompatibility.
```
*******************************************************************************************
The Gradle failure may have been because of AndroidX incompatibilities in this Flutter app.
See https://goo.gl/CP92wY for more information on the problem and how to fix it.
*******************************************************************************************
Gradle task assembleDebug failed with exit code 1
```

**Comment by delay** [comment]
I debug in iOS.  However a few things to try.  Flutter clean and then rebuild in case of a code signing error.  Also try and use a newer version of the included packages if it exists. Look in the pubspec.yaml. Also did you setup firebase at google for this project and place the firebase config file that needs to be installed.  Look at step 6 of this article for how to do that.  
https://medium.com/flutterpub/flutter-how-to-do-user-login-with-firebase-a6af760b14d5

**Comment by Rickem** [comment]
Follow these steps to migrate a Flutter app to AndroidX
https://flutter.dev/docs/development/packages-and-plugins/androidx-compatibility

This worked for me:
1- Open the android folder inside the project with Android Studio
2- Wait for android studio to finish indexing
3- Refactor > Migrate to Android X
