### ISSUE TITLE
Error in Flushbar code 

### ISSUE THREAD

**Issue by UnluckyY1** [delay/flutter_firebase_auth_example#2]
Please help didnt know what is the issue exactly but those errors showing up in 
forgot_password.dart, sign_in.dart, and sign_up.dart

'title', a final variable, can only be set once.dart(assignment_to_final_local)
'message', a final variable, can only be set once.dart(assignment_to_final_local)
'duration', a final variable, can only be set once.dart(assignment_to_final_local)

**Comment by delay** [comment]
It seems flushbar changed their code... you can update the code like so...

```
 Flushbar(
          title: "Sign In Error",
          message: exception,
          duration: Duration(seconds: 5),
        )..show(context);
```

**Comment by delay** [comment]
Updated the code to work with current flushbar.

**Comment by UnluckyY1** [comment]
Hey thank you for replaying i already figured it out last night and fix it  the problem now is with androidx cannot build ...
"Building after running flutter packages get fails because of AndroidX incompatibility." 
I already followed all the instructions for fixing the issue but nothing working yet...
