### ISSUE TITLE
Firebase Auth not listening user status

### ISSUE THREAD

**Issue by FilipeOS** [delay/flutter_firebase_auth_example#7]
Hi @delay ,

I'm having an issue. I'm trying to get the online/offline status but I'm not beeing able and I think it's because the app don't listen to Firebase user status, because when I go to Firebase Auth console the last time I was connected was when I made the login last time (days).

How can we fix it?

**Comment by delay** [comment]
You can use this function to get the current user status from firebase.  getCurrentFirebaseUser() in auth.dart file. Auth.getCurrentFirebaseUser().  However the proper way to handle this is with streams.  I am going to make a new version of this package using streams, however I don't have an ETA of when that will be released yet.

**Comment by FilipeOS** [comment]
@delay Thank you. Stream on the main() or everywhere?

I tried to follow this [tutorial ](https://www.youtube.com/watch?v=nxu4bMpPvCQ) but I need some lights please or I'm stuck.

**Comment by FilipeOS** [comment]
@delay How about create this on the `auth.dart`:

```
static Stream<String> get onAuthStateChanged {
    return FirebaseAuth.instance.onAuthStateChanged.map((FirebaseUser user) => user?.uid);
  }
```

And on main (or whatever) replace this:
```
@override
  Widget build(BuildContext context) {
    appState = StateWidget.of(context).state;
    if (!appState.isLoading && (appState.firebaseUserAuth == null || appState.user == null)) {
      return MaterialApp(
        title: title,
        debugShowCheckedModeBanner: false,
        theme: buildTheme(),
        home: SignInScreen(),
      );
    } else {
      return MaterialApp(
        title: title,
        debugShowCheckedModeBanner: false,
        theme: buildTheme(),
        home: MessagesScreen(),
      );
    }
  }
```

by this:
```
@override
  Widget build(BuildContext context) {
    return StreamBuilder<Object>(
        stream: Auth.onAuthStateChanged,
        builder: (context, snapshot) {
          if (snapshot.connectionState == ConnectionState.active){
            final bool isLoggedIn = snapshot.hasData;
            return isLoggedIn ? MessagesScreen() : SignInScreen();

          }
        }
      );
  }
```

I'm just not sure about the `initUser()` in `state_widget.dart`

**Comment by FilipeOS** [comment]
Hi @delay ,

What's the difference between [this ](https://medium.com/flutter-community/flutter-firebase-login-using-provider-package-54ee4e5083c7) provider and your example? Could you adapt it to use onAuthStateChanged according it?

**Comment by delay** [comment]
Provider is a nice package.  I did not know about it when I made this.  You may want to use that example code instead.  I would say if I was redoing my code today, I would use provider.  I may release a version which uses provider in the future but it's not trivial to use this instead....

**Comment by FilipeOS** [comment]
@delay I just want to check the user presence, I can do this with Observer(AppLifecycleState) but will require to use the exact same code on screens to check when use is with app open or closed (online/offline) and save on Firestore.

Every example I see on web it's of a single screen and not how it will looks like on the others, of if the code repeats too

**Comment by delay** [comment]
So in my main.dart I would add something like this where you put all your providers. This will wrap your entire app so you can access it from anywhere in your app.
```
class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [
        StreamProvider<User>.value(stream: UserData<User>(collection: 'users').userRef.documentStream),
        StreamProvider<FirebaseUser>.value(stream: AuthService().user)
      ],
```
Then in each function you want to use it in, you reference it like this.

``` 
   User user = Provider.of<User>(context);
    FirebaseUser firebaseUser = Provider.of<FirebaseUser>(context);

```
I am not an expert in the provider package... That is just how I am doing it in a different project I am working on.

**Comment by simeon105** [comment]
Why is this not working and it is showing error: FirebaseUser user = await FirebaseAuth.instance
        .createUserWithEmailAndPassword(email: email, password: password); ??

**Comment by FilipeOS** [comment]
> Why is this not working and it is showing error: FirebaseUser user = await FirebaseAuth.instance
> .createUserWithEmailAndPassword(email: email, password: password); ??

@simeon105 Open a new Issue with the log. And debug, debug a lot because you will need it

**Comment by simeon105** [comment]
I fixed that, but now for Sign in it shows me this error:  NoSuchMethodError: The getter 'data' was called on null.

??
