### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by kieth1205** [delay/flutter_firebase_auth_example#8]
I saw an error when sign in with succesfull sign up account. I use may firebase json to manage account, so I saw account succesfull created, but cannot sign with it. Could you tell me why?

**Comment by kieth1205** [comment]
I delete themeform and it run

**Comment by simeon105** [comment]
Please, can you tell me how you fixed that???  Because I still cannot sign in..

**Comment by kieth1205** [comment]
have you added firebase file?
